apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaletestapp
spec:
  selector:
    matchLabels:
      app: scaletestapp
  template:
    metadata:
      labels:
        app: scaletestapp 
    spec:
      containers:
      - name: shestera-scaletestapp
        image: shestera/scaletestapp
        ports:
        - name: web
          containerPort: 8080
        resources:
          requests:
            memory: "10Mi"
          limits:
            memory: "20Mi" 