apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: scaletestapp
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: scaletestapp
  podMetricsEndpoints:
  - port: web