apiVersion: v1
kind: Service
metadata:
  name: scaletestapp
  labels:
    app: scaletestapp
    prometheus-monitored: "true"
spec:
  selector:
    app: scaletestapp
  ports:
  - name: web
    port: 8080