defaultRules:
  create: false
alertmanager:
  enabled: false
grafana:
  enabled: false
kubeApiServer:
  enabled: false
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
prometheus:
  enabled: true
  additionalServiceMonitors:
    - name: app-sm
      namespace: default
      labels:
        serviceMonitorSelector: prometheus
      endpoints:
        - interval: 10s
          targetPort: 8080
          path: /metrics
      namespaceSelector:
        matchNames:
          - default
      selector:
        matchLabels:
          prometheus-monitored: "true" 